name: Build CS3

on:
  push:
    branches: [ main, work ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Android platforms and build-tools
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build plugin
        run: |
          ./gradlew --version
          ./gradlew :app:packageReleasePlugin --stacktrace --no-daemon
      - name: Collect artifact
        run: |
          mkdir -p build-artifacts
          cs3=$(find app -type f -name "*.cs3" | head -n 1)
          if [ -z "$cs3" ]; then echo "No .cs3 built"; exit 1; fi
          cp "$cs3" build-artifacts/gramflix-all.cs3
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gramflix-plugin
          path: build-artifacts/gramflix-all.cs3
