name: Release CS3

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Android platforms and build-tools
        env:
          SKIP_JDK_VERSION_CHECK: "true"
        run: |
          sdkmanager --install "platforms;android-33" "build-tools;33.0.2"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build plugin
        run: |
          ./gradlew :app:packageReleasePlugin --stacktrace --no-daemon || ./gradlew :app:assembleRelease --stacktrace --no-daemon
      - name: Prepare artifact
        id: prep
        run: |
          file=$(find app -type f -name '*.cs3' | head -n 1)
          if [ -z "$file" ]; then echo "No .cs3 built"; exit 1; fi
          cp "$file" gramflix-all.cs3
          echo "file=gramflix-all.cs3" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.prep.outputs.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
