name: Build and Release CS3

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build plugin (release)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
          arguments: :app:packageReleasePlugin --stacktrace
      - name: Prepare artifact name
        shell: bash
        run: |
          set -euo pipefail
          f=$(ls app/build/outputs/plugin/**/*.cs3 | head -n1)
          echo "Found: $f"
          mkdir -p dist
          cp "$f" dist/gramflix-all.cs3
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: cs3-plugin
          path: dist/gramflix-all.cs3
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cs3-plugin
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: dist/gramflix-all.cs3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
